name: Salesforce CI/CD Pipeline to QA

on:
  push:
    branches:
      - main  # triggers when code is pushed to main

jobs:
  pmd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PMD Static Code Analysis
        run: |
          pmd.bat check -d force-app/main/default -R pmd-ruleset.xml -f text

  deploy-qa:
    needs: pmd-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: forcedotcom/sfdx-action@v1.2.0

      - name: Authenticate QA Org
        run: |
          sfdx auth:login -r https://test.salesforce.com -u ${{ secrets.QA_SF_USERNAME }} -p ${{ secrets.QA_SF_PASSWORD }}

      - name: Deploy to QA Org
        run: |
          sfdx force:source:deploy -p force-app/main/default -u ${{ secrets.QA_SF_USERNAME }} -w 10
