name: Deploy to QA Developer Org

on:
  push:
    branches:
      - main

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SF CLI
      uses: patrykacc/sf-cli-setup@v1.1.0

    - name: Authenticate to QA Org
      run: |
        sf org login password \
          --username ${{ secrets.SF_USERNAME_QA }} \
          --password ${{ secrets.SF_PASSWORD_QA }} \
          --instance-url ${{ secrets.SF_LOGIN_URL }} \
          --set-default \
          --alias QA

    - name: Deploy metadata to QA
      run: |
        sf project deploy start \
          --source-dir force-app \
          --target-org QA \
          --wait 10 \
          --verbose
